package sistema.reservas.Presentation.Categoria;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import sistema.reservas.Logic.CategoriaRecurso;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;

public class CategoriaPanel implements PropertyChangeListener {

    private JPanel panel1;
    private JTextField txtBuscarDescripcion;
    private JButton btnBuscar;
    private JButton btnImprimir;
    private JTextField txtId;
    private JTextField txtDescripcion;
    private JButton btnGuardar;
    private JButton btnBorrar;
    private JButton btnLimpiar;
    private JTable tabla;

    private DefaultTableModel tableModel;

    // MVC
    private CategoriaModel model;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public CategoriaPanel() {
        tableModel = new DefaultTableModel(new String[]{"ID", "Descripcion"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                // La edicion real se hace por formulario (boton "Guardar"),
                // no directamente en la celda de la tabla.
                return false;
            }
        };
        tabla.setModel(tableModel);
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        txtId.setEditable(false);
    }

    public JPanel getPanel1() {
        return panel1;
    }

    // --- MVC: enlace con el Model ---

    public void setModel(CategoriaModel model) {
        this.model = model;
        model.addPropertyChangeListener(this);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        switch (evt.getPropertyName()) {
            case CategoriaModel.CATEGORIAS:
                actualizarTabla(model.getCategorias());
                break;
            case CategoriaModel.CURRENT:
                CategoriaRecurso actual = model.getCurrent();
                if (actual == null) {
                    limpiarFormulario();
                } else {
                    cargarFormulario(actual.getId(), actual.getDescripcion());
                }
                break;
        }
    }

    private void actualizarTabla(List<CategoriaRecurso> categorias) {
        tableModel.setRowCount(0);
        for (CategoriaRecurso c : categorias) {
            tableModel.addRow(new Object[]{c.getId(), c.getDescripcion()});
        }
    }

    // --- Getters usados por el Controller ---

    public JTextField getTxtBuscarDescripcion() { return txtBuscarDescripcion; }
    public JButton getBtnBuscar() { return btnBuscar; }
    public JButton getBtnImprimir() { return btnImprimir; }

    public JTextField getTxtId() { return txtId; }
    public JTextField getTxtDescripcion() { return txtDescripcion; }

    public JButton getBtnGuardar() { return btnGuardar; }
    public JButton getBtnBorrar() { return btnBorrar; }
    public JButton getBtnLimpiar() { return btnLimpiar; }

    public JTable getTabla() { return tabla; }
    public DefaultTableModel getTableModel() { return tableModel; }

    /** Limpia el formulario para cargar una nueva categoria. */
    public void limpiarFormulario() {
        txtId.setText("");
        txtDescripcion.setText("");
    }

    /** Carga los datos de una categoria seleccionada en el formulario. */
    public void cargarFormulario(int id, String descripcion) {
        txtId.setText(String.valueOf(id));
        txtDescripcion.setText(descripcion);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 1, new Insets(5, 5, 5, 5), -1, -1));

        final JPanel panelBusqueda = new JPanel();
        panelBusqueda.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        panelBusqueda.setBorder(BorderFactory.createTitledBorder("Busqueda"));
        panel1.add(panelBusqueda, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel labelBuscarDescripcion = new JLabel();
        labelBuscarDescripcion.setText("Descripcion:");
        panelBusqueda.add(labelBuscarDescripcion, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtBuscarDescripcion = new JTextField();
        panelBusqueda.add(txtBuscarDescripcion, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnBuscar = new JButton();
        btnBuscar.setText("Buscar");
        panelBusqueda.add(btnBuscar, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnImprimir = new JButton();
        btnImprimir.setText("Imprimir");
        panelBusqueda.add(btnImprimir, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        final JPanel panelForm = new JPanel();
        panelForm.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelForm.setBorder(BorderFactory.createTitledBorder("Categoria"));
        panel1.add(panelForm, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel labelId = new JLabel();
        labelId.setText("ID:");
        panelForm.add(labelId, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtId = new JTextField();
        panelForm.add(txtId, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, -1), null, 0, false));
        final JLabel labelDescripcion = new JLabel();
        labelDescripcion.setText("Descripcion:");
        panelForm.add(labelDescripcion, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtDescripcion = new JTextField();
        panelForm.add(txtDescripcion, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, -1), null, 0, false));

        final JPanel panelBotonesForm = new JPanel();
        panelBotonesForm.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panelForm.add(panelBotonesForm, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGuardar = new JButton();
        btnGuardar.setText("Guardar");
        panelBotonesForm.add(btnGuardar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnBorrar = new JButton();
        btnBorrar.setText("Borrar");
        panelBotonesForm.add(btnBorrar, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnLimpiar = new JButton();
        btnLimpiar.setText("Limpiar");
        panelBotonesForm.add(btnLimpiar, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tabla = new JTable();
        scrollPane1.setViewportView(tabla);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}