package sistema.reservas.Presentation.Login;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import sistema.reservas.Logic.Usuario;
import sistema.reservas.Presentation.Usuario.UsuarioController;
import javax.swing.*;
import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

public class LoginView extends JDialog implements PropertyChangeListener {

    private JPanel contentPane;
    private JTextField txtUsuario;
    private JPasswordField txtPassword;
    private JLabel lblMensaje;
    private JButton btnIngresar;
    private JButton btnCambiar;

    private boolean authenticated = false;

    // MVC
    private UsuarioController controller;
    private LoginModel model;

    public LoginView() {
        // owner null + modal true: bloquea la aplicacion hasta que se cierre,
        // tal como pide el profesor para el Login.
        super((Frame) null, "Sistema de Reserva de Recursos - Login", true);
        setContentPane(contentPane);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(340, 200);
        setLocationRelativeTo(null);
        setResizable(false);

        btnIngresar.addActionListener(e -> intentarLogin());
    }

    private void intentarLogin() {
        try {
            String username = txtUsuario.getText();
            String password = new String(txtPassword.getPassword());

            Usuario usuario = controller.login(username, password);

            model.setCurrent(usuario);
            authenticated = true;
            mostrarMensaje(" ");
            dispose();

        } catch (Exception ex) {
            mostrarMensaje(ex.getMessage());
        }
    }

    // --- MVC: enlace con Controller y Model ---

    public void setController(UsuarioController controller) {
        this.controller = controller;
    }

    public void setModel(LoginModel model) {
        this.model = model;
        model.addPropertyChangeListener(this);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        // El boton "Ingresar" ya maneja el flujo de exito/error directamente.
    }

    // --- Getters usados por el Controller (ej. para "Cambiar clave") ---

    public String getUsuario() {
        return txtUsuario.getText();
    }

    public char[] getPassword() {
        return txtPassword.getPassword();
    }

    public JButton getBtnCambiar() {
        return btnCambiar;
    }

    public boolean isAuthenticated() {
        return authenticated;
    }

    /**
     * Para que el controller muestre errores de login sin usar JOptionPane.
     */
    public void mostrarMensaje(String mensaje) {
        lblMensaje.setText(mensaje);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 2, new Insets(10, 10, 10, 10), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Usuario:");
        contentPane.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtUsuario = new JTextField();
        contentPane.add(txtUsuario, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Contraseña:");
        contentPane.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPassword = new JPasswordField();
        contentPane.add(txtPassword, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblMensaje = new JLabel();
        lblMensaje.setForeground(new Color(-65536));
        lblMensaje.setText(" ");
        contentPane.add(lblMensaje, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnIngresar = new JButton();
        btnIngresar.setText("Ingresar");
        contentPane.add(btnIngresar, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCambiar = new JButton();
        btnCambiar.setText("Cambiar clave");
        contentPane.add(btnCambiar, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}