package sistema.reservas.Presentation.Actividad;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.table.DefaultTableModel;

import javax.swing.*;
import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

public class ViewActividad implements PropertyChangeListener {

    // Se movió aquí desde ControllerActividad: formatear cómo se ve
    // cada columna (nombre del día) es responsabilidad de la View.
    private static final String[] NOMBRES_DIA = {
            "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"
    };

    private JPanel panel1;
    private JTextField txtFechaReferencia;
    private JButton btnCargar;
    private JButton btnImprimir;
    private JLabel fechaDeReferenciaLabel;
    private JTable tabla;
    private JScrollPane Lineas;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1, -1));
        fechaDeReferenciaLabel = new JLabel();
        fechaDeReferenciaLabel.setText("Fecha de referencia");
        panel1.add(fechaDeReferenciaLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtFechaReferencia = new JTextField();
        txtFechaReferencia.setText("");
        panel1.add(txtFechaReferencia, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnCargar = new JButton();
        btnCargar.setText("Cargar");
        panel1.add(btnCargar, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnImprimir = new JButton();
        btnImprimir.setText("Imprimir");
        panel1.add(btnImprimir, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(2, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        Lineas = new JScrollPane();
        scrollPane1.setViewportView(Lineas);
        tabla = new JTable();
        Lineas.setViewportView(tabla);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private DefaultTableModel tableModel;
    private ModelActividad model;

    public ViewActividad() {
        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.setModel(tableModel);
    }

    public void setModel(ModelActividad model) {
        this.model = model;
        model.addPropertyChangeListener(this);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (ModelActividad.MATRIZ.equals(evt.getPropertyName())) {
            pintarMatriz(model.getMatriz());
        }
    }

    /**
     * Antes vivía en ControllerActividad; pintar la tabla es responsabilidad de la View.
     */
    private void pintarMatriz(MatrizActividad matriz) {
        tableModel.setRowCount(0);
        tableModel.setColumnCount(0);

        tableModel.addColumn("Hora");

        List<LocalDate> dias = matriz.getDias();
        for (LocalDate dia : dias) {
            String nombreDia = NOMBRES_DIA[dia.getDayOfWeek().getValue() - 1];
            tableModel.addColumn(nombreDia + " " + dia);
        }

        List<LocalTime> horas = matriz.getHoras();
        int cantidadDias = dias.size();

        for (int fila = 0; fila < horas.size(); fila++) {
            Object[] filaDatos = new Object[cantidadDias + 1];
            filaDatos[0] = horas.get(fila).toString();
            for (int columna = 0; columna < cantidadDias; columna++) {
                filaDatos[columna + 1] = matriz.getCelda(fila, columna);
            }
            tableModel.addRow(filaDatos);
        }
    }

    public JPanel getPanel1() {
        return panel1;
    }

    public JTextField getTxtFechaReferencia() {
        return txtFechaReferencia;
    }

    public JButton getBtnCargar() {
        return btnCargar;
    }

    public JButton getBtnImprimir() {
        return btnImprimir;
    }

    public JTable getTabla() {
        return tabla;
    }

    public DefaultTableModel getTableModel() {
        return tableModel;
    }
}